V1
saasquatch/dom-context pull request #1
Opened 2020-11-02 17:50 UTC by loganvolkers

## Description of the change

First version

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

 - Jira issue number: (PUT IT HERE)
 - Process.st launch checklist: (PUT IT HERE)

## Checklists

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist
- [ ] "Ready for review" label attached to the PR and reviewers pinged on Slack

### Code review 

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

2021-01-11 23:39 UTC, johanventer requested changes
Looks good, some commented out scenarios in the tests.

2021-01-11 23:39 UTC, johanventer commented on __tests__/Connection.feature
> +    #     Then the listener should reconnect to provider A
Commented out scenarios

2021-01-12 23:55 UTC, johanventer submitted a review, later dismissed

2021-01-13 00:26 UTC, loganvolkers commented on __tests__/Connection.feature
> +    #     Then the listener should reconnect to provider A
Patched jest cucumber to avoid comments

2021-01-13 00:27 UTC, johanventer approved these changes

2021-01-13 00:40 UTC, merged